### ISSUE TITLE
Nexus does not work on iOS 16

### ISSUE THREAD

**Issue by iCrazeiOS** [Loy6410/ios16-tweaks#1]
Nexus does not work on iOS 16, on any jailbreak.

Please remove it from the list, to stop people being sent to safe mode

Though Rune does (also on Havoc) 😉

**Comment by zeco07** [comment]
I bought it because I heard Nexus tweak works on Ios16 but it doesn't work at all!
😡😡

**Comment by iCrazeiOS** [comment]
> I bought it because I heard Nexus tweak works on Ios16 but it doesn't work at all!
> 
> 😡😡

I can refund you if you reply with your transaction ID. Just know that the Havoc website lists the maximum supported iOS versions for each of my tweaks.

**Comment by zeco07** [comment]
I bought it by my mistake, but thank you so much for the refund. bt6pjf5vc5@privaterelay.appleid.com This is the ID I bought

**Comment by iCrazeiOS** [comment]
That's not the transaction ID. You should be able to find it within the confirmation email, or in your Havoc purchases list.

It's a long string of letters/numbers, probably starting with a 6.

**Comment by zeco07** [comment]
Oops sorry I found the correct transaction ID: 659e47341cdfbe9065c4fb95

**Comment by iCrazeiOS** [comment]
Refunded

**Comment by Loy6410** [comment]
> Nexus does not work on iOS 16, on any jailbreak.
> 
> 
> 
> Please remove it from the list, to stop people being sent to safe mode
> 
> 
> 
> Though Rune does (also on Havoc) 😉 

thanks for confirming this, i also put a not currently working tweaks list and the reason why they don't work. If someone wants to update their tweak to support iOS 16 I will update the list
