### ISSUE TITLE
Prysm does not seem to work

### ISSUE THREAD

**Issue by parkerdangaruss** [Loy6410/ios16-tweaks#12]
Attempting to use prysm caused me to get booted to safe mode. Had to convert Al dependencies and prysm. Prysm and prefixui(dependency) could only be converted using the convert simple tweaks option. Libspark(dependency) could be converted with the usually rootless compact layer.

**Comment by Loy6410** [comment]
> Attempting to use prysm caused me to get booted to safe mode. Had to convert Al dependencies and prysm. Prysm and prefixui(dependency) could only be converted using the convert simple tweaks option. Libspark(dependency) could be converted with the usually rootless compact layer.

thanks for confirming!
