### ISSUE TITLE
Dynamic Stage does not work

### ISSUE THREAD

**Issue by iiieq** [Loy6410/ios16-tweaks#15]
Freezes phone after install then restarts

**Comment by Loy6410** [comment]
> Freezes phone after install then restarts

like after you respring in sileo it reboots or after you install it freezes and then reboots device?

**Comment by iiieq** [comment]
after respring it freezes then restarts

**Comment by Loy6410** [comment]
> after respring it freezes then restarts

ok, thanks for testing it
