### ISSUE TITLE
How to add PoomSmart's Repo

### ISSUE THREAD

**Issue by Tgod1991** [Loy6410/ios16-tweaks#16]
Not sure if this is allowed. Most likely "spam" , however, I can't seem to find the correct URL to add the repo to Sileo/Zebra

**Comment by Loy6410** [comment]
> Not sure if this is allowed. Most likely "spam" , however, I can't seem to find the correct URL to add the repo to Sileo/Zebra

don't worry, you can add the url https://poomsmart.github.io/repo/ for poomsmart repo, also on https://www.ios-repo-updates.com you can find every repo and tweak
