### ISSUE TITLE
Some tweaks that work

### ISSUE THREAD

**Issue by NotADevBtw** [Loy6410/ios16-tweaks#21]
Zetsu (Rootfull)
Lynx (didn’t try everything but the options I tried seems to work)
Alpine
TweakSettings (app)
Elysian (theme)

Edit: Turning on floating dock in Lynx settings causes springboard to crash, might be because of other dock tweaks

**Comment by biggiecam** [comment]
More tweaks that's are working. 
-aquaboardXS
-Glow
Both from Elias Limneos have some glitching but they do work. 
Tested on iOS 16.5 iPhone 14 pro max
