### ISSUE TITLE
BigSurCenter not activating

### ISSUE THREAD

**Issue by Slaurits** [Loy6410/ios16-tweaks#25]
Seems that BigSurCenter won't activate correctly on serotonin.

iPhone X iOS 16.6.1

**Comment by Loy6410** [comment]
> Seems that BigSurCenter won't activate correctly on serotonin.
> 
> iPhone X iOS 16.6.1

you are sure you have bought it?

**Comment by Slaurits** [comment]
> > Seems that BigSurCenter won't activate correctly on serotonin.
> > 
> > iPhone X iOS 16.6.1
> 
> you are sure you have bought it?

Yea, i have a recept if you want.
The first time I installed it, it asked me to go to settings and activate, I did so and pressed activate and tried to use it. But after a respring, it just keeps asking.

I can try and make a screen recording of it. Also I'm unable to press activate again, since in the settings tab of the tweak, it just shows the settings of it.

Sorry about bad punctuation, it's close to midnight and I've been up all night.

![image](https://github.com/Loy6410/ios16-tweaks/assets/83727223/ed6eeaa1-0e08-4ee8-bf9d-e5ce2bf7f280)
![image](https://github.com/Loy6410/ios16-tweaks/assets/83727223/d97e1db0-c2f3-4c19-91ea-545ce21e9d33)
![image](https://github.com/Loy6410/ios16-tweaks/assets/83727223/6cc29fcb-6d5b-48e5-b589-d4609dd82b1a)

**Comment by Loy6410** [comment]
> > > Seems that BigSurCenter won't activate correctly on serotonin.
> > > 
> > > iPhone X iOS 16.6.1
> > 
> > you are sure you have bought it?
> 
> Yea, i have a recept if you want.
> The first time I installed it, it asked me to go to settings and activate, I did so and pressed activate and tried to use it. But after a respring, it just keeps asking.
> 
> I can try and make a screen recording of it. Also I'm unable to press activate again, since in the settings tab of the tweak, it just shows the settings of it.
> 
> Sorry about bad punctuation, it's close to midnight and I've been up all night.
> 
> ![image](https://github.com/Loy6410/ios16-tweaks/assets/83727223/ed6eeaa1-0e08-4ee8-bf9d-e5ce2bf7f280)
> ![image](https://github.com/Loy6410/ios16-tweaks/assets/83727223/d97e1db0-c2f3-4c19-91ea-545ce21e9d33)
> ![image](https://github.com/Loy6410/ios16-tweaks/assets/83727223/6cc29fcb-6d5b-48e5-b589-d4609dd82b1a)

i think you're right, and the developer might need to update the activation thing in settings, thanks for telling and good night!
