### ISSUE TITLE
More tweaks that work

### ISSUE THREAD

**Issue by NotADevBtw** [Loy6410/ios16-tweaks#26]
AirDrop16 | Repo: Havoc (converting the tweak from Havoc will cause it to not work, there’s a working .deb on a Google Drive by the developer which still needs the tweak to be purchased on Havoc)

BigSurCenter | Repo: Havoc

CozyBadges | Repo: https://b4db1r3.github.io/d3vr3p0/

Kayoko | Repo: https://github.com/vyolit/Kayoko (seems to only work in apps with tweak injection enabled)

MusicArtworkSave-Rootless | Repo: ETHN’s 
Repo

Senri | Repo: Chariz

Ve | Repo: https://github.com/vyolit/Ve

Zetsu does work (stated as not working) but the rootfull package should be installed, the rootless package do crash however

Tweaks that doesn’t work:

Diary | Repo: https://github.com/vyolit/Diary

Any foxfortmobile tweak (seems like the libraries needed by the tweaks causes a reboot as soon as springboard tweak injection is enabled)

**Comment by davidkh88** [comment]
Your iOS version? And are you using RootHide's Bootstrap or Serotonin?

**Comment by NotADevBtw** [comment]
> Your iOS version? And are you using RootHide's Bootstrap or Serotonin?

iOS 16.5.1 using Serotonin

**Comment by Loy6410** [comment]
> AirDrop16 | Repo: Havoc (converting the tweak from Havoc will cause it to not work, there’s a working .deb on a Google Drive by the developer which still needs the tweak to be purchased on Havoc)
> 
> BigSurCenter | Repo: Havoc
> 
> CozyBadges | Repo: https://b4db1r3.github.io/d3vr3p0/
> 
> Kayoko | Repo: https://github.com/vyolit/Kayoko (seems to only work in apps with tweak injection enabled)
> 
> MusicArtworkSave-Rootless | Repo: ETHN’s Repo
> 
> Senri | Repo: Chariz
> 
> Ve | Repo: https://github.com/vyolit/Ve
> 
> Zetsu does work (stated as not working) but the rootfull package should be installed, the rootless package do crash however
> 
> Tweaks that doesn’t work:
> 
> Diary | Repo: https://github.com/vyolit/Diary
> 
> Any foxfortmobile tweak (seems like the libraries needed by the tweaks causes a reboot as soon as springboard tweak injection is enabled)

can i ask what's the issue with diary?

**Comment by NotADevBtw** [comment]
> 
> can i ask what's the issue with diary?

It just doesn’t work, not sure if it’s the tweak itself or the fact that the tweak settings page causes the settings app to crash so it can’t be enabled (if it’s disabled by default)
