### ISSUE TITLE
IOS 16 Serotonin-Compatible Tweaks Google Spreadsheet

### ISSUE THREAD

**Issue by e16130209** [Loy6410/ios16-tweaks#30]
Hi Loy6410,

I'm seeing that this isn't being updated with the tweaks people have posted in the Issues section, I've added everything I can find to this spreadsheet.

https://docs.google.com/spreadsheets/d/1iKEIsAq2ZADHOO_nR6En9tCPNqGYwUdM3wXW4qKjN5w/edit?usp=sharing

**Comment by Loy6410** [comment]
> Hi Loy6410,
> 
> 
> 
> I'm seeing that this isn't being updated with the tweaks people have posted in the Issues section, I've added everything I can find to this spreadsheet.
> 
> 
> 
> https://docs.google.com/spreadsheets/d/1iKEIsAq2ZADHOO_nR6En9tCPNqGYwUdM3wXW4qKjN5w/edit?usp=sharing
> 
> 

i will update the list with new tweaks and better tabs subdivisions, thanks
