### ISSUE TITLE
Piracy Repo (HackYouriPhone)

### ISSUE THREAD

**Issue by ghost** [Loy6410/ios16-tweaks#34]
Since there's no other good list like this for semi-jailbreak related tweaks and the tweak that is in HackYouriPhone's repo doesn't work can you remove anything related to that so I can easily share this list for people interested in Seretonin and other jailbreaks?

**Comment by Loy6410** [comment]
> Since there's no other good list like this for semi-jailbreak related tweaks and the tweak that is in HackYouriPhone's repo doesn't work can you remove anything related to that so I can easily share this list for people interested in Seretonin and other jailbreaks?

sorry i didn't notice it was there, the repo as you said doesn't even work and i'll not add any pirated repos, thanks for telling me

**Comment by ghost** [comment]
thanks broski I appreciate it
