### ISSUE TITLE
MilkyWay 4 not working on IOS 16.0 iPhone 12 pro max serotonin

### ISSUE THREAD

**Issue by KUchuna** [Loy6410/ios16-tweaks#7]
Tweak gets installed and it is shown in settings, but after enabling and respringing there is no option added in 3D touch menu, to launch apps in window mode.

**Comment by Loy6410** [comment]
> Tweak gets installed and it is shown in settings, but after enabling and respringing there is no option added in 3D touch menu, to launch apps in window mode.

ok as it happens for me, thanks for confirming
