### ISSUE TITLE
[Help] Filza iOS 16.6?

### ISSUE THREAD

**Issue by Tgod1991** [Loy6410/ios16-tweaks#8]
How does one install filza on the newly semi jb Serotonin?

**Comment by Loy6410** [comment]
> How does one install filza on the newly semi jb Serotonin?

idk if you can, just install it with trollstore

**Comment by Tgod1991** [comment]
> > How does one install filza on the newly semi jb Serotonin?
> 
> idk if you can, just install it with trollstore

I have it installed now. Had to download the ipa of the filza site that was specifically for TrollStore. Thank you
