### ISSUE TITLE
iGameGod (Rootless)

### ISSUE THREAD

**Issue by Tgod1991** [Loy6410/ios16-tweaks#9]
This tweak (cheat engine) is working for me from their own repo  https://iosgods.com/repo/

Wasn't sure where to request for something to be added

EDIT: THIS IS NOT WORKING. NO GAMES ARE RECOGNIZED

**Comment by imnltsa** [comment]
iGameGod doesn't work because it only targets user applications, which isn't possible on the roothide Bootstrap. You CAN inject the dylib into .ipa files and install with TrollStore, however.
